import {Caption} from '../captions';

// Script de la voix-off « Comment réussir son intégration HSE » et timings (secondes).
export const captions: Caption[] = [
  {text: "Tu viens d'être nommé", start: 0.0, end: 1.3},
  {text: "responsable *HSE ?*", start: 1.3, end: 3.1},
  {text: "L'erreur classique", start: 3.1, end: 4.0},
  {text: "pour s'imposer,", start: 4.0, end: 4.8},
  {text: "c'est de vouloir tout", start: 4.8, end: 5.8},
  {text: "*révolutionner*", start: 5.8, end: 6.8},
  {text: "et de déployer une", start: 6.8, end: 7.9},
  {text: "*avalanche* de nouvelles", start: 7.9, end: 8.8},
  {text: "procédures dès les", start: 8.8, end: 9.8},
  {text: "premières semaines.", start: 9.8, end: 11.2},
  {text: "Mais débarquer sur", start: 11.2, end: 12.2},
  {text: "le terrain avec une", start: 12.2, end: 12.9},
  {text: "pile d'exigences inédites", start: 12.9, end: 14.4},
  {text: "crée instantanément", start: 14.4, end: 15.4},
  {text: "un *blocage.*", start: 15.4, end: 16.6},
  {text: "Les équipes se braquent,", start: 16.6, end: 17.7},
  {text: "car ces règles ignorent", start: 17.7, end: 18.7},
  {text: "totalement l'historique", start: 18.7, end: 19.9},
  {text: "et la réalité de l'usine.", start: 19.9, end: 21.8},
  {text: "La *réussite* exige une", start: 21.8, end: 23.1},
  {text: "approche *mesurée.*", start: 23.1, end: 24.5},
  {text: "Sur votre plan d'intégration", start: 24.5, end: 25.8},
  {text: "des *30 premiers jours,*", start: 25.8, end: 27.2},
  {text: "la phase initiale est", start: 27.2, end: 28.2},
  {text: "une stricte *immersion.*", start: 28.2, end: 29.2},
  {text: "Arpenter les *ateliers,*", start: 29.2, end: 31.0},
  {text: "écouter les *travailleurs*", start: 31.0, end: 31.9},
  {text: "et décortiquer les", start: 31.9, end: 33.0},
  {text: "anciens *rapports.*", start: 33.0, end: 34.3},
  {text: "Passer ensuite ces données", start: 34.3, end: 35.3},
  {text: "dans un *filtre*", start: 35.3, end: 36.0},
  {text: "de *priorisation.*", start: 36.0, end: 37.5},
  {text: "L'objectif n'est pas", start: 37.5, end: 38.4},
  {text: "de tout corriger", start: 38.4, end: 39.0},
  {text: "d'un coup,", start: 39.0, end: 39.7},
  {text: "mais d'isoler uniquement", start: 39.7, end: 40.9},
  {text: "les *trois à cinq* risques", start: 40.9, end: 42.0},
  {text: "les plus *critiques*", start: 42.0, end: 42.7},
  {text: "pour la *sécurité.*", start: 42.7, end: 44.2},
  {text: "C'est sur ce socle restreint", start: 44.2, end: 45.4},
  {text: "que vous bâtissez", start: 45.4, end: 46.0},
  {text: "votre premier *plan d'action.*", start: 46.0, end: 47.8},
  {text: "En ciblant exclusivement", start: 47.8, end: 49.0},
  {text: "ces quelques urgences", start: 49.0, end: 49.9},
  {text: "*prioritaires,*", start: 49.9, end: 50.8},
  {text: "toutes validées par", start: 50.8, end: 51.5},
  {text: "l'expérience réelle", start: 51.5, end: 52.3},
  {text: "du *terrain,*", start: 52.3, end: 53.3},
  {text: "vos directives deviennent", start: 53.3, end: 54.2},
  {text: "instantanément *légitimes*", start: 54.2, end: 55.5},
  {text: "et les équipes adoptent", start: 55.5, end: 56.7},
  {text: "naturellement cette", start: 56.7, end: 57.5},
  {text: "nouvelle *culture*", start: 57.5, end: 58.0},
  {text: "de *prévention.*", start: 58.0, end: 59.2},
];
