import {Caption} from '../captions';

// Script de la voix-off « Agent ou Superviseur HSE : qui fait quoi ? » et timings (secondes).
export const captions: Caption[] = [
  {text: 'Sur les chantiers comme', start: 0.2, end: 1.0},
  {text: 'dans les usines,', start: 1.0, end: 2.1},
  {text: 'on confond très', start: 2.1, end: 2.8},
  {text: 'souvent deux piliers', start: 2.8, end: 3.7},
  {text: 'de la prévention', start: 3.7, end: 4.3},
  {text: 'des risques…', start: 4.3, end: 5.1},
  {text: "…l'*Agent HSE* et le", start: 5.1, end: 6.5},
  {text: '*Superviseur HSE.*', start: 6.5, end: 8.5},
  {text: 'Pourtant,', start: 8.5, end: 8.9},
  {text: 'leurs responsabilités', start: 8.9, end: 9.8},
  {text: 'sont bien', start: 9.8, end: 10.2},
  {text: '*distinctes.*', start: 10.2, end: 11.5},
  {text: "L'*Agent HSE,*", start: 11.5, end: 12.9},
  {text: "c'est véritablement", start: 12.9, end: 13.7},
  {text: "l'*œil du terrain.*", start: 13.7, end: 15.0},
  {text: 'Sa mission principale', start: 15.0, end: 15.9},
  {text: 'se déroule dans', start: 15.9, end: 16.5},
  {text: "l'*action immédiate.*", start: 16.5, end: 17.9},
  {text: 'Il inspecte les', start: 17.9, end: 18.7},
  {text: 'installations,', start: 18.7, end: 19.7},
  {text: 'vérifie le bon', start: 19.7, end: 20.5},
  {text: 'port des *EPI,*', start: 20.5, end: 21.8},
  {text: 'anime les causeries', start: 21.8, end: 22.5},
  {text: 'de sécurité et signale', start: 22.5, end: 24.0},
  {text: 'la moindre situation', start: 24.0, end: 24.9},
  {text: '*dangereuse.*', start: 24.9, end: 26.5},
  {text: 'De son côté,', start: 26.5, end: 27.8},
  {text: 'le *Superviseur HSE*', start: 27.8, end: 29.0},
  {text: 'prend de la *hauteur.*', start: 29.0, end: 30.3},
  {text: 'Sa fonction', start: 30.3, end: 30.7},
  {text: 'première,', start: 30.7, end: 31.1},
  {text: "c'est la", start: 31.1, end: 31.4},
  {text: '*coordination.*', start: 31.4, end: 32.9},
  {text: 'Il organise le', start: 32.9, end: 33.6},
  {text: 'travail des agents,', start: 33.6, end: 35.0},
  {text: "veille à l'application", start: 35.0, end: 36.0},
  {text: 'rigoureuse des mesures', start: 36.0, end: 36.8},
  {text: 'correctives et analyse', start: 36.8, end: 38.4},
  {text: 'la *performance*', start: 38.4, end: 39.0},
  {text: 'globale du site.', start: 39.0, end: 41.1},
  {text: 'En résumé :', start: 41.1, end: 42.2},
  {text: 'la base *observe,*', start: 42.2, end: 43.3},
  {text: '*contrôle et alerte.*', start: 43.3, end: 44.9},
  {text: 'Le niveau supérieur', start: 44.9, end: 45.9},
  {text: '*planifie,*', start: 45.9, end: 46.9},
  {text: '*supervise* et', start: 46.9, end: 47.7},
  {text: '*fait appliquer.*', start: 47.7, end: 49.5},
  {text: 'Bien sûr,', start: 49.5, end: 49.9},
  {text: 'selon la taille', start: 49.9, end: 50.5},
  {text: 'de la structure,', start: 50.5, end: 51.4},
  {text: 'ces deux rôles', start: 51.4, end: 51.9},
  {text: 'peuvent parfois', start: 51.9, end: 52.4},
  {text: "*s'entrecroiser.*", start: 52.4, end: 53.9},
  {text: 'Vous savez désormais', start: 53.9, end: 54.7},
  {text: 'identifier votre place', start: 54.7, end: 55.8},
  {text: 'exacte dans la', start: 55.8, end: 56.5},
  {text: '*chaîne de sécurité.*', start: 56.5, end: 58.2},
  {text: 'Alors,', start: 58.2, end: 58.6},
  {text: 'vous êtes plutôt', start: 58.6, end: 59.5},
  {text: '*action terrain* ou', start: 59.5, end: 60.6},
  {text: '*pilotage global ?*', start: 60.6, end: 61.6},
];
