import {Caption} from '../captions';

// Script de la voix-off « Pourquoi la prévention rapporte gros » et timings (secondes)
// relevés sur la vidéo d'origine. Les mots entre *astérisques* sont surlignés.
export const captions: Caption[] = [
  {text: "L'économie de la", start: 0.0, end: 0.8},
  {text: '*prévention* le démontre', start: 0.8, end: 1.8},
  {text: 'clairement :', start: 1.8, end: 2.6},
  {text: 'la sécurité au', start: 2.6, end: 3.4},
  {text: 'travail *rapporte*', start: 3.4, end: 4.3},
  {text: "*de l'argent.*", start: 4.3, end: 5.6},
  {text: 'Pourtant,', start: 5.6, end: 6.1},
  {text: 'beaucoup de dirigeants', start: 6.1, end: 6.8},
  {text: 'perçoivent encore', start: 6.8, end: 7.5},
  {text: 'les normes HSE comme', start: 7.5, end: 8.5},
  {text: 'une simple *charge*', start: 8.5, end: 9.1},
  {text: '*administrative.*', start: 9.1, end: 11.1},
  {text: 'Prenons le cas', start: 11.1, end: 11.6},
  {text: "précis d'un *accident*", start: 11.6, end: 12.3},
  {text: '*grave* survenant', start: 12.3, end: 13.0},
  {text: 'sur une chaîne', start: 13.0, end: 13.5},
  {text: 'de production.', start: 13.5, end: 15.0},
  {text: 'Le premier choc', start: 15.0, end: 15.5},
  {text: 'financier est *immédiat.*', start: 15.5, end: 17.1},
  {text: 'Les urgences et', start: 17.1, end: 17.7},
  {text: 'arrêts médicaux', start: 17.7, end: 18.6},
  {text: 'siphonnent directement', start: 18.6, end: 19.4},
  {text: 'la *trésorerie.*', start: 19.4, end: 21.1},
  {text: 'Mais cette facture', start: 21.1, end: 21.7},
  {text: 'initiale cache un', start: 21.7, end: 22.5},
  {text: 'véritable *gouffre* :', start: 22.5, end: 23.9},
  {text: "la machine à l'arrêt", start: 23.9, end: 25.1},
  {text: 'et la chute brutale', start: 25.1, end: 25.9},
  {text: 'de *productivité.*', start: 25.9, end: 27.9},
  {text: "L'hémorragie se", start: 27.9, end: 28.6},
  {text: 'poursuit à long terme,', start: 28.6, end: 29.6},
  {text: 'avec des cotisations', start: 29.6, end: 30.5},
  {text: "d'assurance accident", start: 30.5, end: 31.4},
  {text: 'du travail qui', start: 31.4, end: 32.3},
  {text: '*explosent* la', start: 32.3, end: 32.8},
  {text: 'masse salariale.', start: 32.8, end: 34.8},
  {text: 'Opposons toutes ces', start: 34.8, end: 35.6},
  {text: 'pertes vertigineuses', start: 35.6, end: 37.0},
  {text: 'à un *investissement*', start: 37.0, end: 37.9},
  {text: 'ciblé :', start: 37.9, end: 39.0},
  {text: "l'installation d'un", start: 39.0, end: 39.8},
  {text: '*garde-corps* protecteur', start: 39.8, end: 41.1},
  {text: 'avant le drame.', start: 41.1, end: 42.9},
  {text: 'Mathématiquement,', start: 42.9, end: 43.9},
  {text: '*chaque euro investi*', start: 43.9, end: 45.0},
  {text: 'proactivement pour', start: 45.0, end: 45.8},
  {text: 'sécuriser neutralise', start: 45.8, end: 47.4},
  {text: 'une réaction en', start: 47.4, end: 48.1},
  {text: 'chaîne de coûts', start: 48.1, end: 49.4},
  {text: 'incontrôlables.', start: 49.4, end: 50.3},
  {text: 'Et que se passe-t-il', start: 50.3, end: 51.1},
  {text: 'pour notre', start: 51.1, end: 51.5},
  {text: 'accident industriel', start: 51.5, end: 52.2},
  {text: 'du départ ?', start: 52.2, end: 53.8},
  {text: 'Le *garde-corps* a', start: 53.8, end: 54.5},
  {text: 'bloqué la chute,', start: 54.5, end: 55.6},
  {text: "l'employé est", start: 55.6, end: 56.3},
  {text: '*indemne,*', start: 56.3, end: 56.9},
  {text: 'et le budget', start: 56.9, end: 57.6},
  {text: 'reste *intact.*', start: 57.6, end: 58.6},
];
