// Timeline de la narration (durées réelles de la voix de synthèse masculine).
export const NARR_END = 110.34;
export const SEG: Record<string, {start: number; end: number; text: string}> = {
  h1: {start: 0.6, end: 3.36, text: "Un accident du travail, ce n'est pas un simple formulaire."},
  h2: {start: 3.68, end: 5.28, text: "C'est une course contre la montre."},
  h3: {start: 5.6, end: 7.5, text: "Et derrière chaque délai, il y a une personne."},
  m0: {start: 8.3, end: 9.99, text: "Voici les cinq étapes, de A à Z."},
  m1: {start: 10.31, end: 13.19, text: "L'accident. Les obligations. Le médecin. L'enquête. La rechute."},
  m2: {start: 13.51, end: 14.33, text: "C'est parti !"},
  a0: {start: 15.63, end: 17.6, text: "Étape un : c'est quoi, un accident du travail ?"},
  a1: {start: 17.92, end: 19.28, text: "Retenez la règle de trois."},
  a2: {start: 19.63, end: 21.62, text: "Un : un événement soudain, daté, localisé."},
  a3: {start: 21.92, end: 24.1, text: "Deux : il survient sous l'autorité de l'employeur."},
  a4: {start: 24.4, end: 26.33, text: "Trois : une lésion, physique ou psychologique."},
  a5: {start: 26.65, end: 29.79, text: "Un seul critère manque ? Ce n'est pas un accident du travail. Point."},
  o0: {start: 31.09, end: 32.5, text: "Étape deux : le chrono démarre !"},
  o1: {start: 32.82, end: 35.63, text: "Le salarié a vingt-quatre heures pour prévenir son employeur."},
  o2: {start: 35.95, end: 39.62, text: "L'employeur, lui, a quarante-huit heures pour envoyer la déclaration à la CPAM."},
  o3: {start: 39.94, end: 44.18, text: "Il remet la feuille d'accident à la victime : ses soins sont pris en charge, sans avance de frais."},
  o4: {start: 44.5, end: 48.54, text: "Et en cas d'arrêt, il transmet l'attestation de salaire, pour les indemnités journalières."},
  d0: {start: 49.84, end: 51.65, text: "Étape trois : le médecin tient la plume."},
  d1: {start: 51.97, end: 54.82, text: "Certificat initial : il fige la situation, le jour J."},
  d2: {start: 55.14, end: 57.97, text: "Certificat de prolongation : la guérison prend plus de temps."},
  d3: {start: 58.29, end: 60.22, text: "Certificat final : l'état est stabilisé."},
  d4: {start: 60.54, end: 63.62, text: "Et le certificat de rechute, si tout se dégrade après la clôture."},
  e0: {start: 64.92, end: 66.76, text: "Étape quatre : la CPAM mène l'enquête."},
  e1: {start: 67.08, end: 69.96, text: "Des réserves de l'employeur ? Des faits flous ? Le dossier est instruit."},
  e2: {start: 70.28, end: 73.31, text: "Vient alors la phase contradictoire. Dix jours. Pas un de plus."},
  e3: {start: 73.63, end: 77.18, text: "Employeur et salarié consultent les pièces, et ajoutent leurs observations."},
  e4: {start: 77.5, end: 79.31, text: "Ensuite seulement, la décision tombe."},
  r0: {start: 80.61, end: 81.96, text: "Étape cinq : la rechute."},
  r1: {start: 82.46, end: 85.11, text: "Environ quinze pour cent des accidents du travail rechutent."},
  r2: {start: 85.43, end: 89.13, text: "Surtout dans le BTP et l'industrie, où la douleur peut se taire pendant des mois."},
  r3: {start: 89.45, end: 91.39, text: "Pour être reconnue, encore trois conditions."},
  r4: {start: 91.64, end: 93.65, text: "Un lien direct avec l'accident d'origine."},
  r5: {start: 93.9, end: 95.85, text: "Une aggravation réelle de l'état de santé."},
  r6: {start: 96.1, end: 98.51, text: "Et aucune consolidation définitive auparavant."},
  r7: {start: 99.61, end: 102.73, text: "Dès le certificat reçu, la caisse a soixante jours pour statuer."},
  f1: {start: 104.03, end: 106.11, text: "Alors, un dossier clos, est-ce vraiment une victoire ?"},
  f2: {start: 106.43, end: 108.76, text: "Le suivi ne s'arrête pas au certificat final."},
  f3: {start: 109.08, end: 110.34, text: "La prévention non plus."},
};
