// Timeline de la narration (générée à partir des durées réelles de la voix de synthèse).
export const NARR_END = 147.78;
export const SEG: Record<string, {start: number; end: number; text: string}> = {
  intro: {start: 1.2, end: 4.25, text: "Position latérale de sécurité à deux secouristes."},
  c1: {start: 5.2, end: 10.75, text: "Une victime a perdu connaissance. Elle respire, mais vous suspectez un traumatisme du rachis."},
  c2: {start: 11.1, end: 14.64, text: "Vous avez évalué ses fonctions vitales et alerté le quinze."},
  c3: {start: 14.99, end: 21.39, text: "La régulation médicale vous demande de la placer en position latérale de sécurité, à deux secouristes."},
  c4: {start: 21.74, end: 25.54, text: "Si c'est indiqué, un collier cervical est posé avant la manœuvre."},
  r1: {start: 26.79, end: 29.97, text: "Le secouriste un, placé à la tête, guide la manœuvre."},
  r2: {start: 30.32, end: 33.82, text: "Il maintient la tête du début à la fin, sans jamais la relâcher."},
  r3: {start: 34.17, end: 36.77, text: "Le secouriste deux réalise le retournement."},
  p0: {start: 38.02, end: 39.62, text: "Étape un : la préparation."},
  p1: {start: 39.97, end: 45.05, text: "Le secouriste deux prépare un coussin, qui servira à caler la tête après le retournement."},
  p2: {start: 45.4, end: 49.33, text: "Il rapproche délicatement les jambes de la victime dans l'axe du corps."},
  p3: {start: 49.68, end: 54.59, text: "Il place le bras, côté retournement, à angle droit, paume de la main tournée vers le haut."},
  p4: {start: 54.94, end: 60.61, text: "Puis il saisit l'autre avant-bras, et amène le dos de la main contre l'oreille, côté retournement."},
  p5: {start: 60.96, end: 63.73, text: "Le secouriste un maintient cette main sous la sienne."},
  p6: {start: 64.08, end: 69.73, text: "Le secouriste deux se place à genoux, assez loin de la victime pour la tourner sans avoir à reculer."},
  p7: {start: 70.08, end: 72.85, text: "Il saisit la hanche d'une main, et l'épaule de l'autre."},
  t0: {start: 74.1, end: 75.66, text: "Étape deux : le retournement."},
  t1: {start: 76.01, end: 78.38, text: "Le secouriste un donne des ordres clairs."},
  t2: {start: 78.88, end: 80.65, text: "Attention. Pour tourner. Tournez !"},
  t3: {start: 81.3, end: 88.66, text: "Le secouriste deux tire en même temps sur la hanche et sur l'épaule, bras tendus, et amène la victime d'un seul bloc sur le côté."},
  t4: {start: 89.01, end: 94.09, text: "Le secouriste un accompagne la tête dans le même mouvement, en évitant toute torsion du cou."},
  t5: {start: 94.44, end: 102.8, text: "En cas de difficulté, le genou opposé peut être fléchi avant le retournement, comme pour la position latérale de sécurité à un secouriste."},
  s0: {start: 104.05, end: 105.91, text: "Étape trois : la stabilisation."},
  s1: {start: 106.26, end: 110.01, text: "Le secouriste deux tient la hanche avec la main qui tenait l'épaule."},
  s2: {start: 110.36, end: 116.06, text: "De sa main libre, il fléchit le genou de la victime à angle droit, pour stabiliser la position."},
  s3: {start: 116.41, end: 120.61, text: "Il vérifie que la bouche est ouverte, et que la victime respire toujours."},
  s4: {start: 120.96, end: 125.1, text: "Si le coussin n'a pas été placé avant, il est glissé sous la tête maintenant."},
  s5: {start: 125.45, end: 128.2, text: "Le secouriste un reste en maintien de la tête."},
  s6: {start: 128.55, end: 133.09, text: "Si la victime présente des lésions, couchez-la autant que possible sur le côté atteint."},
  k0: {start: 134.34, end: 135.3, text: "À retenir."},
  k1: {start: 135.65, end: 138.87, text: "La position est stable, et la plus latérale possible."},
  k2: {start: 139.22, end: 143.23, text: "La respiration et la liberté des voies aériennes peuvent être contrôlées."},
  k3: {start: 143.58, end: 146.93, text: "Et l'écoulement des sécrétions vers l'extérieur est favorisé."},
};
export const ORDER = ["intro", "c1", "c2", "c3", "c4", "r1", "r2", "r3", "p0", "p1", "p2", "p3", "p4", "p5", "p6", "p7", "t0", "t1", "t2", "t3", "t4", "t5", "s0", "s1", "s2", "s3", "s4", "s5", "s6", "k0", "k1", "k2", "k3"];
