import {Caption} from '../captions';

// Script de la voix-off « L'architecture d'une équipe HSE performante » et timings (secondes)
// relevés sur la vidéo d'origine. Les mots entre *astérisques* sont surlignés.
export const captions: Caption[] = [
  {text: 'Gérer la *sécurité*', start: 0.1, end: 1.0},
  {text: 'sur un site', start: 1.0, end: 1.5},
  {text: 'industriel complexe,', start: 1.5, end: 2.6},
  {text: "ce n'est pas juste", start: 2.6, end: 3.3},
  {text: 'empiler des *règles.*', start: 3.3, end: 4.8},
  {text: "Comment s'assurer", start: 4.8, end: 5.3},
  {text: "qu'une politique", start: 5.3, end: 6.1},
  {text: 'pensée dans des', start: 6.1, end: 6.7},
  {text: 'bureaux protège', start: 6.7, end: 7.4},
  {text: 'réellement le travailleur', start: 7.4, end: 8.3},
  {text: 'sur le *chantier ?*', start: 8.3, end: 9.5},
  {text: "L'architecture repose", start: 9.5, end: 10.4},
  {text: 'sur *six maillons.*', start: 10.4, end: 11.7},
  {text: 'Tout au sommet,', start: 11.7, end: 12.5},
  {text: 'le *Responsable*', start: 12.5, end: 13.1},
  {text: '*HSE* pilote le', start: 13.1, end: 14.0},
  {text: 'système global.', start: 14.0, end: 15.2},
  {text: 'Il ne gère pas', start: 15.2, end: 15.6},
  {text: 'le quotidien :', start: 15.6, end: 16.6},
  {text: 'il élabore la *stratégie*', start: 16.6, end: 17.9},
  {text: 'et garantit la', start: 17.9, end: 18.8},
  {text: 'stricte *conformité.*', start: 18.8, end: 20.4},
  {text: 'Ensuite,', start: 20.4, end: 21.1},
  {text: 'cette vision', start: 21.1, end: 21.6},
  {text: 'doit descendre.', start: 21.6, end: 22.9},
  {text: 'Le *Coordonnateur*', start: 22.9, end: 23.9},
  {text: 'harmonise les procédures', start: 23.9, end: 25.0},
  {text: 'entre les différents', start: 25.0, end: 25.7},
  {text: 'services…', start: 25.7, end: 26.5},
  {text: '…tandis que le', start: 26.5, end: 27.1},
  {text: '*Superviseur* prend le', start: 27.1, end: 28.0},
  {text: 'relais sur le site', start: 28.0, end: 28.7},
  {text: 'pour encadrer', start: 28.7, end: 29.3},
  {text: 'directement les équipes', start: 29.3, end: 30.2},
  {text: 'opérationnelles.', start: 30.2, end: 32.0},
  {text: 'Mais pour anticiper', start: 32.0, end: 32.7},
  {text: "l'accident au plus", start: 32.7, end: 33.4},
  {text: 'près des machines,', start: 33.4, end: 34.5},
  {text: 'le système déploie', start: 34.5, end: 35.3},
  {text: 'un *œil expert.*', start: 35.3, end: 36.7},
  {text: "L'*Agent HSE* inspecte", start: 36.7, end: 37.9},
  {text: 'les installations,', start: 37.9, end: 39.0},
  {text: 'détecte la moindre', start: 39.0, end: 39.9},
  {text: 'faille et intervient', start: 39.9, end: 40.9},
  {text: 'immédiatement', start: 40.9, end: 41.5},
  {text: 'face au risque.', start: 41.5, end: 42.7},
  {text: "L'efficacité de", start: 42.7, end: 43.4},
  {text: 'cette structure', start: 43.4, end: 44.1},
  {text: "exige que l'information", start: 44.1, end: 45.1},
  {text: '*remonte* sans', start: 45.1, end: 45.6},
  {text: 'aucune friction.', start: 45.6, end: 46.7},
  {text: 'Intégré aux équipes,', start: 46.7, end: 47.9},
  {text: 'le *Relais* signale les', start: 47.9, end: 48.9},
  {text: 'situations dangereuses', start: 48.9, end: 49.7},
  {text: 'depuis le cœur', start: 49.7, end: 50.3},
  {text: 'même du chantier.', start: 50.3, end: 51.5},
  {text: 'Plus haut,', start: 51.5, end: 52.2},
  {text: "l'*Assistant HSE*", start: 52.2, end: 53.6},
  {text: 'centralise toutes ces', start: 53.6, end: 54.7},
  {text: 'observations et produit', start: 54.7, end: 55.7},
  {text: 'les *statistiques*', start: 55.7, end: 56.3},
  {text: 'pour la direction.', start: 56.3, end: 57.5},
  {text: "Ce n'est donc pas une", start: 57.5, end: 58.2},
  {text: 'simple hiérarchie', start: 58.2, end: 59.1},
  {text: 'administrative…', start: 59.1, end: 60.3},
  {text: "…c'est un", start: 60.3, end: 60.7},
  {text: '*circuit fermé.*', start: 60.7, end: 61.9},
  {text: 'Les *directives* protègent', start: 61.9, end: 62.9},
  {text: 'les opérateurs,', start: 62.9, end: 63.9},
  {text: 'et les réalités du', start: 63.9, end: 64.8},
  {text: '*terrain* perfectionnent', start: 64.8, end: 65.6},
  {text: 'la *stratégie.*', start: 65.6, end: 66.4},
];
