// Sous-titres et timings (secondes) relevés sur la capsule d'origine.
// Ils servent aussi de script de voix-off.
export type Caption = {text: string; start: number; end: number};

export const captions: Caption[] = [
  {text: 'Le *Superviseur HSE.*', start: 0.0, end: 2.1},
  {text: 'Son seul objectif ?', start: 2.1, end: 3.7},
  {text: "S'assurer que", start: 3.7, end: 4.4},
  {text: 'chaque travailleur', start: 4.4, end: 5.3},
  {text: 'rentre chez lui', start: 5.3, end: 6.0},
  {text: '*sain et sauf.*', start: 6.0, end: 7.9},
  {text: 'Pour y arriver,', start: 7.9, end: 8.8},
  {text: 'il ne reste pas', start: 8.8, end: 9.3},
  {text: 'au bureau.', start: 9.3, end: 10.2},
  {text: 'Il est omniprésent', start: 10.2, end: 11.0},
  {text: 'sur le *terrain.*', start: 11.0, end: 12.0},
  {text: 'Il traque les', start: 12.0, end: 12.5},
  {text: '*dangers,*', start: 12.5, end: 13.1},
  {text: 'mène des inspections', start: 13.1, end: 14.1},
  {text: 'et corrige les gestes', start: 14.1, end: 15.0},
  {text: 'en temps réel.', start: 15.0, end: 16.3},
  {text: 'Avant toute', start: 16.3, end: 16.8},
  {text: 'opération critique,', start: 16.8, end: 17.8},
  {text: "c'est lui qui a", start: 17.8, end: 18.4},
  {text: 'le *dernier mot.*', start: 18.4, end: 19.5},
  {text: 'Soudure,', start: 19.5, end: 20.1},
  {text: 'levage,', start: 20.1, end: 20.8},
  {text: 'espace confiné…', start: 20.8, end: 21.9},
  {text: 'rien ne démarre sans', start: 21.9, end: 22.7},
  {text: 'sa validation du', start: 22.7, end: 23.5},
  {text: '*permis de travail.*', start: 23.5, end: 25.1},
  {text: 'Il orchestre aussi', start: 25.1, end: 25.9},
  {text: 'les exercices', start: 25.9, end: 26.5},
  {text: "d'urgence et surveille", start: 26.5, end: 27.9},
  {text: 'le tri des déchets', start: 27.9, end: 28.5},
  {text: 'industriels.', start: 28.5, end: 30.1},
  {text: 'Mais attention à', start: 30.1, end: 31.0},
  {text: 'ne pas le confondre', start: 31.0, end: 31.7},
  {text: 'avec le', start: 31.7, end: 32.0},
  {text: '*Responsable HSE.*', start: 32.0, end: 33.5},
  {text: 'Ce dernier pilote', start: 33.5, end: 34.3},
  {text: 'le système,', start: 34.3, end: 35.1},
  {text: 'décortique les', start: 35.1, end: 35.7},
  {text: 'chiffres et conseille', start: 35.7, end: 36.5},
  {text: 'la direction.', start: 36.5, end: 37.7},
  {text: 'Le Superviseur,', start: 37.7, end: 38.4},
  {text: 'lui,', start: 38.4, end: 38.9},
  {text: "vit dans *l'action.*", start: 38.9, end: 40.3},
  {text: 'Il observe,', start: 40.3, end: 41.0},
  {text: 'alerte et fait', start: 41.0, end: 41.8},
  {text: 'appliquer les règles.', start: 41.8, end: 43.7},
  {text: 'Les manuels de sécurité', start: 43.7, end: 44.8},
  {text: 'ne sauvent aucune', start: 44.8, end: 45.6},
  {text: 'vie à eux seuls.', start: 45.6, end: 46.7},
  {text: "C'est le Superviseur", start: 46.7, end: 47.5},
  {text: 'HSE qui transforme', start: 47.5, end: 48.5},
  {text: 'cette théorie en', start: 48.5, end: 49.3},
  {text: 'un véritable *bouclier*', start: 49.3, end: 50.3},
  {text: '*protecteur* pour', start: 50.3, end: 50.9},
  {text: 'ses équipes.', start: 50.9, end: 51.6},
];
